namespace AISServer.Components.Io.Enums
{
    public enum ProfibusInputId
    {
        // SYSTEM BLOCK
        USER_DOOR_NOT_CLOSED = 0,
        FRONT_DOOR_NOT_CLOSED = 1,
        REAR_DOOR_NOT_CLOSED = 2,
        UPSTREAM_TRAY_AVAILABLE = 3,
        DOWNSTREAM_ACCEPT_TRAY = 4,
        SURGE_OK = 5,

        SEED_DROP1_COUNTER_VALUE = 6,
        SEED_DROP2_COUNTER_VALUE = 7,
        SEED_DROP3_COUNTER_VALUE = 8,
        SEED_DROP4_COUNTER_VALUE = 9,
        SEED_DROP5_COUNTER_VALUE = 10,
        SEED_DROP6_COUNTER_VALUE = 11,

        // SAFETY BLOCK
        ESTOP_USER_DOOR_NOT_PRESSED = 12,
        ESTOP_INFEED_NOT_PRESSED = 13,
        ESTOP_REAR_NOT_PRESSED = 14,
        ESTOP_UPSTREAM_NOT_PRESSED = 15,
        ESTOP_DOWNSTREAM_NOT_PRESSED = 16,

        USER_DOOR_CLOSED_LOCKED = 17,
        FRONT_DOOR_CLOSED_LOCKED = 18,
        REAR_DOOR_CLOSED_LOCKED = 19,

        USER_DOOR_PUSHBUTTON = 20,
        FRONT_DOOR_PUSHBUTTON = 21,
        REAR_DOOR_PUSHBUTTON = 22,
        BYPASS_STATE = 23,

        ESTOP_RELAYS_GOOD = 24,
        DOOR_RELAYS_GOOD = 25,
        RESET_NOT_NEEDED = 26,

        // ABOVE DECK
        VSTACK_OPLATE_MOVER_IMAGING = 27,
        VSTACK_OPLATE_MOVER_VSTACK = 28,
        OPLATE_IMAGING_1_DETECTED = 29,
        OPLATE_IMAGING_2_DETECTED = 30,
        IMAGING_OPLATE_UNCLAMPED = 31,
        IMAGING_OPLATE_CLAMPED = 32,
        DELIDDER_DISCARD = 33,
        DELIDDER_PICKUP = 34,
        DELIDDER_HAS_LID = 35,
        VSTACK_OPLATE_TOO_TALL = 36,
        FLIPPER_OPLATE_MOVER_IMAGING = 37,
        FLIPPER_OPLATE_MOVER_FLIPPER = 38,
        ON_WHEEL_SENSOR = 39,
        FLIPPER_COVER_CLOSED = 40,
        FLIPPER_COVER_OPEN = 41,
        FLIPPER_UNCLAMPED = 42,
        FLIPPER_CLAMPED = 43,
        FLIPPER_LOAD = 44,
        FLIPPER_DUMP = 45,
        FLIPPER_HAS_OPLATE = 46,
        FLIPPER_SEED_DUMP_CLOSED = 47,

        ABOVE_REVOLVER_GATE_CLOSED = 48,
        ABOVE_REVOLVER_GATE_OPENED = 49,
        DIVERTER_RIGHT_GATE_CLOSED = 50,
        DIVERTER_RIGHT_GATE_OPENED = 51,
        DIVERTER_LEFT_GATE_CLOSED = 52,
        DIVERTER_LEFT_GATE_OPENED = 53,

        DROP_TUBES_DOWN = 54,
        DROP_TUBES_UP = 55,

        VSTACK_OPLATE_HEIGHT_VALUE = 56,
        SINGULATOR_VACUUM_PRESSURE = 57,

        // BELOW DECK
        SHUTTLE_GATE_1_CLOSED = 58,
        SHUTTLE_GATE_1_OPENED = 59,
        SHUTTLE_GATE_2_CLOSED = 60,
        SHUTTLE_GATE_2_OPENED = 61,
        SHUTTLE_GATE_3_CLOSED = 62,
        SHUTTLE_GATE_3_OPENED = 63,
        SHUTTLE_GATE_4_CLOSED = 64,
        SHUTTLE_GATE_4_OPENED = 65,
        SHUTTLE_GATE_5_CLOSED = 66,
        SHUTTLE_GATE_5_OPENED = 67,
        SHUTTLE_GATE_6_CLOSED = 68,
        SHUTTLE_GATE_6_OPENED = 69,

        SEED_DISCARD_CONTAINER_PRESENT = 70,
        INFEED_TRAY_ENTRY = 71,
        INFEED_TRAY_EXIT = 72,
        MAIN_CONVEYOR_ENTRY = 73,
        MAIN_CONVEYOR_DROP_TUBES = 74,
        MAIN_CONVEYOR_EXIT = 75,
        QUEUE_BIN_LEFT_CLOSED = 76,
        QUEUE_BIN_RIGHT_CLOSED = 77,
        QUEUE_BIN_LEFT_LOCKED = 78,
        QUEUE_BIN_LEFT_UNLOCKED = 79,
        QUEUE_BIN_LEFT_GATE_CLOSED = 80,
        QUEUE_BIN_LEFT_GATE_OPENED = 81,
        QUEUE_BIN_RIGHT_LOCKED = 82,
        QUEUE_BIN_RIGHT_UNLOCKED = 83,
        QUEUE_BIN_RIGHT_GATE_CLOSED = 84,
        QUEUE_BIN_RIGHT_GATE_OPENED = 85,
        DROP_TUBE_ID_SENSOR_1 = 86,
        DROP_TUBE_ID_SENSOR_2 = 87,
        DROP_TUBE_ID_SENSOR_3 = 88
    }
}
